#!/usr/bin/env node
import { readFileSync } from 'node:fs'

const data = JSON.parse(readFileSync('index.json', 'utf8'))
for (const [classifier, ids] of Object.entries(data)) {
  if (ids.length === 0) {
    process.stdout.write(`${classifier}\n`)
  }
}
