#!/usr/bin/env node
import { readFileSync, writeFileSync } from 'node:fs'

const data = JSON.parse(readFileSync('index.json', 'utf8'))
for (const classifier of Object.keys(data)) {
  data[classifier] = data[classifier].sort()
}

writeFileSync('index.json', JSON.stringify(data, null, 2) + '\n')
